### ISSUE TITLE
Transfer from Trello to Git

### ISSUE THREAD

**Issue by NikoGab** [NikoGab/PNE-Data-Analyis#5]
Please Transfer this Trello card to Git:

20-282 - PNE - KI Analyse-Modell für Projekteffizienz

**Comment by michaelbrainer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [20-282 - PNE - KI Analyse-Modell für Projekteffizienz](https://trello.com/c/ZPhEDPiC/155-20-282-pne-ki-analyse-modell-f%C3%BCr-projekteffizienz)
